# Generated by Django 5.1.1 on 2024-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='preschool_charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_code', models.CharField(max_length=255)),
                ('centre_name', models.CharField(max_length=255)),
                ('incidental_charges', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
    ]
