# Generated by Django 5.1.1 on 2024-10-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_school_cca_school_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDB_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('town', models.CharField(max_length=255)),
                ('flat_type', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('storey_range', models.CharField(max_length=255)),
                ('floor_area_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flat_model', models.CharField(max_length=255)),
                ('lease_commence_date', models.IntegerField()),
                ('remaining_lease', models.CharField(max_length=255)),
                ('resale_price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
