# Generated by Django 5.1.1 on 2024-11-11 15:19

from django.db import migrations, models
import django.db.utils

def add_latitude_longitude_columns(apps, schema_editor):
    SchoolInfo = apps.get_model('database', 'school_info')
    db_alias = schema_editor.connection.alias

    # Check if the 'latitude' column exists
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='database_school_info' AND column_name='latitude'
        """)
        if cursor.fetchone() is None:
            cursor.execute("""
                ALTER TABLE database_school_info
                ADD COLUMN latitude DECIMAL(10, 7)
            """)

    # Check if the 'longitude' column exists
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='database_school_info' AND column_name='longitude'
        """)
        if cursor.fetchone() is None:
            cursor.execute("""
                ALTER TABLE database_school_info
                ADD COLUMN longitude DECIMAL(10, 7)
            """)

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_userhdbsearch_userpreschoolsearch_userschoolsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(add_latitude_longitude_columns),
    ]
