# Generated by Django 5.1.1 on 2024-11-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_userhdbsearch_userpreschoolsearch_userschoolsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userschoolsearch',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
