# Generated by Django 5.1.1 on 2024-11-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_place_school_info_latitude_school_info_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_url', models.URLField()),
                ('language', models.CharField(max_length=10)),
                ('original_language', models.CharField(max_length=10)),
                ('profile_photo_url', models.URLField()),
                ('rating', models.IntegerField()),
                ('relative_time_description', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('time', models.BigIntegerField()),
                ('translated', models.BooleanField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='database.place')),
            ],
        ),
    ]
